type Item {
  by: UserById
  descendants: Int
  id: Int
  score: Int
  time: Int
  title: String
  type: Type
  url: String
  parent: Int
  text: String
}

extend type Item {
  comments: [ItemById]
}

extend type Item {
  polloptions: [PollOptionById]
}

type PollOption {
  id: Int
  score: Int
  time: Int
  type: Type
  url: String
  text: String
  poll: Int
}

type PollOptionById {
  id: ID!
  polloption: PollOption
}

extend type Item {
  poll: Int
}

type ItemById {
  id: ID!
  story: Item
}

enum Type {
  job
  story
  comment
  poll
  pollopt
}
